name: Documentation Issue
description: Report an issue with documentation
title: "[DOCS]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README.md
        - README.ru.md
        - CONTRIBUTING.md
        - SECURITY.md
        - Code comments/docstrings
        - API documentation
        - Tutorial/Guide
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue? (file path, section, line number)
      placeholder: |
        File: README.md
        Section: Quick Start
        Lines: 65-70
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Typo/Grammar
        - Incorrect information
        - Missing information
        - Unclear explanation
        - Outdated content
        - Broken link
        - Missing example
        - Translation issue
        - Other
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (copy/paste if possible)
      placeholder: Current text...
    validations:
      required: true

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: How should it be improved?
      placeholder: Suggested text or changes...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue
